### ISSUE TITLE
Resampling with list of patterns

### ISSUE THREAD

**Issue by zcapjdb** [umami-hep/umami-preprocessing#2]
It was recently discovered that changes to the Sample class in ftag-tools caused a list of patterns to no longer be supported. This was fixed in [atlas-ftag-tools/#28](https://github.com/umami-hep/atlas-ftag-tools/pull/28). However it seems that things are still not 100% working as intended. When I start some resampling I can see that the correct number of jets are picked up (I think it's the correct amount as this is mc20+mc21 and the stats here are 2x the default of 40M):
```INFO     Estimated 93,247,500 lowpt_ttbar_cjets jets available - 80,000,000 requested```

However, the resampling eventually crashes like so:
```ValueError: Ran out of lowpt_ttbar_cjets jets after writing 40,192,067```

Which seems like it is reading all the cjets from the mc20 sample and then isn't looking into the mc21 samples I have provided in the config file:
```
ttbar: &ttbar
  name: ttbar
  pattern:
    - user.*.410470.*/*.h5
    - user.*.601230.*/*.h5
    - user.*.601229.*/*.h5
```

tagging @samvanstroud @AndriusVaitkus97
